# Generated by Django 2.2.4 on 2019-09-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50, null=True)),
                ('area', models.CharField(max_length=50, null=True)),
                ('bloque', models.CharField(max_length=50, null=True)),
                ('Respuesta', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
            ],
        ),
    ]
