# Generated by Django 2.2.4 on 2019-09-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_form_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='Cargoform',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='Correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
